name: tadelaktdesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8190521439537406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5915899509564042
  lightness: 0.47136801294982433
  saturation: 0.7700809906236827
  rhythmicContrast: 0.682283294852823
purpose: []
