name: tadelaktdesign
favicon: null
layout_spectrum: 0.62323
typography_spectrum: 0.8190521439537406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feebbc'
    - '#b3a98d'
    - '#326c64'
    - '#bd2240'
    - '#c68a23'
  brandStrength: 0.625
  lightness: 0.47136801294982433
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
